# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20170422_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='StubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='stubset',
            old_name='length',
            new_name='length_from',
        ),
        migrations.AddField(
            model_name='stubset',
            name='length_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='stubset',
            name='stub_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.StubType'),
        ),
    ]
