# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20170422_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='stubset',
            name='finished_number',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
