# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20170423_0522'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
