# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_stub'),
    ]

    operations = [
        migrations.AddField(
            model_name='stub',
            name='stubset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.StubSet'),
            preserve_default=False,
        ),
    ]
