# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=200)),
                ('stat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MechineStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MechineUsageRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stat', models.IntegerField()),
                ('to_stat', models.IntegerField()),
                ('mechine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Mechine')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OperatorStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='mechineusagerecord',
            name='op',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.Operator'),
        ),
    ]
