# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20170430_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechineusagerecord',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mechineusagerecord',
            name='from_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stat', to='operations.MechineStat'),
        ),
        migrations.AlterField(
            model_name='mechineusagerecord',
            name='to_stat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stat', to='operations.MechineStat'),
        ),
    ]
