# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_stub'),
        ('operations', '0003_auto_20170505_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='TampingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mechine_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.MechineUsageRecord')),
                ('stub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Stub')),
            ],
        ),
    ]
