# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_tampingrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tampingrecord',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tampingrecord',
            name='depth_offset',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tampingrecord',
            name='drop_offset',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tampingrecord',
            name='serial_num',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
