# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20170716_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tampingrecord',
            name='serial_num',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
